Code increment #9
besean163/ya-prac-project1 pull request #11
Opened 2024-07-29 13:02 UTC by besean163

2024-08-05 03:28 UTC, vokinneberg requested changes
Поздравляю с первым ревью второго спринта! 🤗 В этом спринте мы охватили большой и важный материал, а наше приложение усложнилось. 💪 Менее мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Твоя реализация достаточно лаконичная и хорошо читается и понимается. 👍
3. Ты реализовал тесты новых хендлеров. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово реализовать тест-кейсы для проверки поддержки сжатия/разжатия контента, а так же негативные сценарии.
2. По условию задачи в случае, если `StoreInterval == 0`, запись в файл должна происходить синхронно, а в твоей реализации запись не будет происходить вообще? Стоит доработать реализацию.

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/flags.go
> +	flag.IntVar(&storeIntervalFlag, "i", 300, "store interval")
Значения по умолчанию можно вынести в константы.

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/main.go
> +	err = storeService.Restore(config.Restore)
Мне кажется логичней либо передавать `config.Restore` в `NewService(...)` и там загружать данные из файла, либо проверять прямо здесь, так как если передать в  `Restore(...)` false, ничего не произойдет, так какой смысл ее вызывать?

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
👍 за использование errgroup.

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/main.go
> +	if config.StoreInterval > 0 {
По условию задачи в случае, если `StoreInterval == 0`, запись в файл должна происходить синхронно, а в твоей реализации  запись не будет происходить вообще?

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/main.go
> +	// нашел этот кусок кода в интернете, понимаю его туманно
Обработка прерываний операционно системы имеет смысл, например в случае, если сервис завершается в ручную, нажатием  Ctrl + C, или же внешние процессы, например kubernetes, могут отравлять сигнал `SIGTERM` приложению для завершения.

2024-08-05 03:28 UTC, vokinneberg commented on cmd/server/main_test.go
> +		{
👍 за реализацию тестов! Было бы здорово так же реализовать тесты для проверки негативных сценариев, а так же сжатия.

2024-08-05 03:28 UTC, vokinneberg commented on internal/handlers/handlers.go
> +func logMiddleware(h http.Handler) http.Handler {
Это не обязательно, но я бы рекомендовал вынести middleware в отдельный файл - этот файл уже разросся и его трудновато читать.

2024-08-05 03:28 UTC, vokinneberg commented on internal/handlers/handlers.go
> +		logger.Get().Info(
Мне кажется, сто стоит логировать запрос и ответ отдельно, так как если в процессе `h.ServeHTTP(lResponseWriter, r)` произойдет сбой, то данные запроса не залогируются.

2024-08-05 03:28 UTC, vokinneberg commented on internal/handlers/logdata.go
> +	// vet говорит что эта строка лишняя, не понимаю почему
У меня не получилось воспроизвести, а что конкретно говорит `go vet`?

2024-08-05 17:54 UTC, besean163 commented on cmd/server/flags.go
> +	flag.IntVar(&storeIntervalFlag, "i", 300, "store interval")
Согласен, поправил

2024-08-05 17:58 UTC, besean163 commented on cmd/server/main.go
> +	if config.StoreInterval > 0 {
Переделал, теперь если 0, то дамп сохраняется при записи метрик

2024-08-05 18:00 UTC, besean163 commented on cmd/server/main.go
> +	// нашел этот кусок кода в интернете, понимаю его туманно
Я понял в целом смысл, просто немного сложны были для понимания контекст и каналы. Текущий спринт просветил)

2024-08-05 18:00 UTC, besean163 commented on internal/handlers/handlers.go
> +func logMiddleware(h http.Handler) http.Handler {
Согласен, перекинул

2024-08-05 18:05 UTC, besean163 commented on cmd/server/main.go
> +	err = storeService.Restore(config.Restore)
Да, поторопился, не подумал( Переделал, теперь как параметр при инициализации хранилища. Единственное, я сделал что при инициализации хранилища, запускается горутина на дамп. Вроде решение рабочее, но режет глаз, аргементов против не нашел и оставил так

2024-08-09 01:23 UTC, vokinneberg commented on internal/inmem/inmem.go
> +		if err := storage.Restore(); err != nil {
👍

2024-08-09 01:23 UTC, vokinneberg commented on internal/inmem/inmem.go
> +	if s.dumpInterval == 0 {
👍

2024-08-09 01:23 UTC, vokinneberg commented on cmd/server/main.go
> +	err = storeService.Restore(config.Restore)
Согласен, что решение не очень хорошее по нескольким причинам на мой взгляд:
- Запускать go-рутину в фабричном методе я бы не стал, так как это очень не явно. Все-таки метод должен делать что-то одно - в данном случае инициализаровать storage (при необходимости восстанавливая его из файла) и возвращать инстанс
- Твоя  go-рутина создается в стиле fire-and-forget, а значит ты теряешь над ней контроль как только ты ее запустил.

Я бы рассмотрел вариант явного старта дампа после создания инстанса, причем подумал бы над тем, как эта горутина будет завершаться в случае завершения приложения.

2024-08-09 01:25 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью второго спринта! 🙌 Ты реализовал мои предложения, и твоя реализация стала соответствовать постановке задачи. Отличная работа! 🚀 Я оставил пару комментариев вернуться к которым мы сможем в 3 спринте. 👍

2024-08-09 07:24 UTC, merged