Code increment #13
besean163/ya-prac-project1 pull request #15
Opened 2024-08-12 16:35 UTC by besean163

2024-08-18 19:13 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты сделал рефакторинг существующих компонентов и улучшил структуру приложения. 🚀

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. По условию задачи `retry` должен осуществляться при получении retriable ошибки, а не безусловно. *Retriable-ошибки — это ошибки, которые могут быть исправлены повторной попыткой выполнения операции.*
2. По условию задачи *изменение в базе можно выполнять в рамках одной транзакции или одного запроса*. Стоит реализовать это требование.
3. Стоит реализовать тест нового хендлера.
4. Стоит консистентно использовать логгер и избавиться от вызовов `fmt.Println(...)`.

2024-08-18 19:13 UTC, vokinneberg commented on internal/services/runtimeService.go
> +	for retry(err) {
По условию задачи `retry` должен осуществляться при получении  retriable ошибки. _Retriable-ошибки — это ошибки, которые могут быть исправлены повторной попыткой выполнения операции._  Вообще достачтоно сложно понять, как работает логика `retry()`, стоит добавить либо комментарий либо тест,

2024-08-18 19:13 UTC, vokinneberg commented on internal/services/runtimeService.go
> +		if err != nil {
Необходимо проверять код ошибки.

2024-08-18 19:13 UTC, vokinneberg commented on cmd/server/main.go
> +	store, err := getStorage(ctx, config)
Не настаиваю, но почему бы нам не создать `*sql.DB` в методе `main` и  не передать его в `getStorage(...)` и `handlers.New(...)`? Мне кажется таким образом можно было убрать дублирующийся код.

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/inmemstorage/inmemstorage.go
> +func (s *Storage) GetMetrics() []*metrics.Metrics {
Так как сам слайс будет передавать по ссылке нет необходимости хранить в слайсе указатели нас структуры, так как копирования все равно не будет происходить, во всяком случае если это не требуется явно.
```suggestion
func (s *Storage) GetMetrics() []metrics.Metrics {
```

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/databasestorage/databasestorage.go
> +func (s *Storage) GetMetrics() []*metrics.Metrics {
Так как сам слайс будет передавать по ссылке нет необходимости хранить в слайсе указатели нас структуры, так как копирования все равно не будет происходить, во всяком случае если это не требуется явно.
```suggestion
func (s *Storage) GetMetrics() []metrics.Metrics {
```

2024-08-18 19:13 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	if hasJSONHeader(r) {
Стоит обработать кейс и вернуть соответствующее сообщение от ошибке если поддерживается только `JSON`. Возвращать просто `200 OK` не информативно и может запутать пользователя.

2024-08-18 19:13 UTC, vokinneberg commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
`chi` должен обработать этот кейс автоматически.

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/databasestorage/databasestorage.go
> +	fmt.Println("metric", metric)
Думаю стоит использовать наш логгер тут?

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/databasestorage/databasestorage.go
> +func (s *Storage) SetMetrics(metrics []metrics.Metrics) error {
По условию задачи _изменение в базе можно выполнять в рамках одной транзакции или одного запроса_. Стоит реализовать это требование.

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/databasestorage/databasestorage.go
> +					fmt.Println("here")
Думаю стоит использовать наш логгер тут?

2024-08-18 19:13 UTC, vokinneberg commented on internal/storage/inmemstorage/inmemstorage.go
> +	metric := s.GetMetric(metricType, name)
Похоже этот код дублируется от стораджа к стораджу. Возможно стоит подумать о том, как его переиспользовать для разных стораджей?

2024-08-19 17:46 UTC, besean163 commented on internal/services/runtimeService.go
> +	for retry(err) {
Показалось хорошей идеей использовать рекурсию, с виду лаконично и просто, возможно замылился глаз и не осознал что со стороны сложно понять( Добавил и комментарии и тест.

2024-08-19 17:46 UTC, besean163 commented on internal/services/runtimeService.go
> +		if err != nil {
Добавил

2024-08-19 18:07 UTC, besean163 commented on cmd/server/main.go
> +	store, err := getStorage(ctx, config)
Да, можно, правда сложно отлавливать в таком случае ошибки при подключении к драйверу, например в хендлере. Я переделал с кастомными ошибками.

2024-08-20 16:53 UTC, besean163 commented on internal/storage/databasestorage/databasestorage.go
> +func (s *Storage) GetMetrics() []*metrics.Metrics {
Да, согласен, переделал.

2024-08-20 16:58 UTC, besean163 commented on internal/storage/databasestorage/databasestorage.go
> +	fmt.Println("metric", metric)
Да, не подчистил после дебага( исправил

2024-08-20 16:58 UTC, besean163 commented on internal/storage/databasestorage/databasestorage.go
> +					fmt.Println("here")
Да, подчистил.

2024-08-20 16:59 UTC, besean163 commented on internal/storage/inmemstorage/inmemstorage.go
> +func (s *Storage) GetMetrics() []*metrics.Metrics {
Согласен, исправил

2024-08-20 17:19 UTC, besean163 commented on internal/storage/databasestorage/databasestorage.go
> +func (s *Storage) SetMetrics(metrics []metrics.Metrics) error {
Да, упустил. Исправил

2024-08-20 17:23 UTC, besean163 commented on internal/handlers/handlers.go
> +	if r.Method != http.MethodPost {
Да, точно, я же естанавливаю хендлер на post, убрал.

2024-08-20 17:30 UTC, besean163 commented on internal/storage/inmemstorage/inmemstorage.go
> +	metric := s.GetMetric(metricType, name)
Не понимаю как использовать одну реализацию для разных стораджей, ведь в базе и инмеме разная логика. Есть две мысли: 
1. искать в слайсе интерфейсного метода GetMetrics
2. добавить в интерфейс сам метод GetMetric
Но мне эти два варианта не кажутся нужными и не вижу с них профита, не стал делать. Буду рад узнать хотя бы направление как сделать правильно, если что я не так понял)

2024-08-22 03:06 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью третьего спринта! 🙌  Отличная работа! 🚀 

2024-08-22 03:06 UTC, vokinneberg commented on internal/storage/inmemstorage/inmemstorage.go
> +	metric := s.GetMetric(metricType, name)
Сейчас посмотрел и видимо мне действительно показалось, что это такие жу похожие блоки кода. 😊

2024-08-22 07:14 UTC, merged